# Generated by Django 4.2.27 on 2026-01-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='orders.autorizacionpresupuestal', verbose_name='Autorización'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='quotations.cotizacionmaterial', verbose_name='Cotización'),
        ),
    ]
